version: '3'

services:
  backend:
    image: leave-backend-e-gov:0.0.1
    volumes:
      - backend_data:/backend-api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=LeaveManagement.settings
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - app-network

  db:
    hostname: postgres_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    networks:
      - app-network
    volumes:
      - pg_data:/var/lib/postgres/data

networks:
  app-network:
    driver: bridge
volumes:
  pg_data:
  backend_data: