version: '3'

services:
  backend:
    image: leave-backend:0.0.1
    #    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./LeaveManagement:/backend-api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=LeaveManagement.settings
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
